### PR TITLE
Checkbox "selectable templates"

### PR DESCRIPTION
**Pull request by dmi3yy**

### CODE REVIEW

**Comment by Deesen** [comment]
I updated a Modx 1.0.15-installation. After update new column "selectable" could not be found so SQL throws an error! But no error while update-procedure. 

Is it the missing linebreak after `#1.1` so `ALTER TABLE` gets ignored? https://github.com/modxcms/evolution/commit/6db670331140e5a7e8b83e03649a963b9e45ed71

**Comment by Deesen** [comment]
For update I used this setup.sql incl. new "Chunk remembers RTE"-feature, which creates also a new column: https://github.com/Deesen/evolution/commit/3001fc647db0d33c06f6f243bbb1e2da0aef9be5

So column `editor_name` was created while updating, but column `selectable` not?

**Comment by dmi3yy** [comment]
add space and test all ok

**Comment by Deesen** [comment]
:+1: :+1:

**Pull request merged**
