### PR TITLE
Allow .svg upload files

### PR DESCRIPTION
**Pull request by fourroses666**

### CODE REVIEW

**Comment by esszett** [comment]
Please revert - I strongly recomment to leave it as "disallow svg" as default. Editors/clients are usually not aware of the filestructure and the possibility of malicious code inside svg. Just google for "svg malicious code".

**Comment by Deesen** [comment]
You can even encapsulate games/apps into SVGs like in Flash? Never heard of before!

**Comment by Deesen** [comment]
http://guya.net/security/svg/chrome_login.svg

**Comment by modxuser** [comment]
+1 @esszett

**Comment by bossloper** [comment]
+1 for removing this as a default. A manager can easily add it in via the System configuration if they really want to (risk it).

**Comment by fourroses666** [comment]
Didn't know

**Pull request merged**
