### PR TITLE
Action 990 for calling modxapi.ajax inside Manager, Dashboard-Buttons "Delete, Publish" ajaxified

### PR DESCRIPTION
**Pull request by Deesen**
I´m not sure if you guys like adding this idea to core. With this PR it is possible to click those 2 buttons without reloading the page. CSS-styles can be toggled as per server-answer (published/deleted = yes/no). The resource-tree also updates accordingly "in realtime".

dash

### CODE REVIEW

**Comment by Nicola1971** [comment]
Great job Deesen!! for me it's a must

Some issue:

1) sometimes dont work on some resources

see video:
https://www.youtube.com/watch?v=nkkp5A7aWhY&feature=youtu.be

2) trash icon not updated for trashed documents

**Comment by pmfx** [comment]
I like it, but I just noticed that there is no confirmation alert when clicking publish/unpublish/delete/undelete and it should be there.

**Comment by Deesen** [comment]
Thanks for testing. The pub_date was the reason why it was not possible to unpublish a date. Is the alert ok like this?

**Comment by Nicola1971** [comment]
now works fine, but notifications must be translatable, otherwise just cause panic to non english customers :D

**Comment by Nicola1971** [comment]
question: does it works with actions for users/webusers too? 

I'm thinking to improve the user mangement

download2

**Comment by Deesen** [comment]
But its already translateable ;-)? Yes the API can be enhanced also for webusers etc in future.

**Comment by Deesen** [comment]
Its not good, the delete-button does not work the same like delete/undelete-processor. It does not delete children or get them back for example like when using context-menu in resource-tree.

**Comment by Deesen** [comment]
I think this is a clean solution. Only issues are, when deleting a container, not all children get updated in resources widget view.. and alert-messages should be same like in resource-tree.

**Comment by Nicola1971** [comment]
it's ok for me

just missing this fix
https://github.com/modxcms/evolution/pull/835/commits/a6ce450ea1f438384dc06245a8dd43d9226f1c9b

**Comment by dmi3yy** [comment]
into 1.2 ? 
or next release?

**Comment by Deesen** [comment]
Please you decide. I´m ok with next release so we have more time to make it "perfect" and to use it with more actions like user-management for @Nicola1971 .

**Comment by dmi3yy** [comment]
I think better add in 1.2.1 
and now only bugfix

**Comment by Deesen** [comment]
I will move it to a new branch and open another PR.

**Comment by Deesen** [comment]
https://github.com/Deesen/evolution/tree/modxapi-ajax

**Pull request closed without merging**
