### PR TITLE
#391 username/data htmlspecialchars

### PR DESCRIPTION
**Pull request by Deesen**

### CODE REVIEW

**Comment by yama** [comment]
Thanks.
Can we use the letters such as "<", ">" and " ' " ?

**Comment by Deesen** [comment]
No, then new problems appear. You are right, issue is not solved. How to follow up? Check Username/Password for valid letters and throw new error message?

Also if you enter "test&test" as name of a user (or any other user-field), input-fields will show `&amp;`. Because the `&amp;` written into database (encoded by function sanitize() in save_user.processor) becomes encoded again after every save-action (`value="&amp;amp;".. "&amp;amp;amp;".. "&amp;amp;amp;amp;"`):

mutate_user.dynamic.php:
`<input name="fullname" value="<?php echo $modx->htmlspecialchars($userdata['fullname']); ?>"..`

**Comment by Deesen** [comment]
I´m working on it and on my local machine it is possible. So inside DB everything is stored as entities with htmlspecialchars() and without striptags() to leave < > intact. When loading from DB all values become entity-decoded first to avoid double-encoding of & amps; (`&amp; &amp;amp;` etc) when saving multiple times. Because for display the data becomes encoded again with `echo htmlspecialchars($userdata['x'])`.

Is it safe or am I opening new security holes this way? From my recherche it should be safe.

**Comment by yama** [comment]
Sorry, It is that it is not necessary to encode password character string that I wanted to say.
Thank you that the encoding of username is necessary.

**Comment by Deesen** [comment]
Ok, tested with username & password = `tes''t<>$&%\/` etc.

**Pull request merged**
