### PR TITLE
Added new roles "assets_images, assets_files" etc.

### PR DESCRIPTION
**Pull request by Deesen**

### CODE REVIEW

**Comment by bossloper** [comment]
Good work. I've not tested yet, but looking at setup.sql, I presume by default after an upgrade (non-admin) managers would not have access to images and files until the permission is manually checked I their role? If so that might be an issue, mainly for the TinyMCE interface where they would have had the browse buttons, but will now not by default.
Also might apply to the default 'Publisher' and 'Editor' roles for the default setup.sql (somewhere around line 825 'REPLACE INTO `{PREFIX}user_roles`'?

**Comment by Deesen** [comment]
Right! To not break permissions after an upgrade maybe changing DEFAULT to 1 is enough? This way it should behave like before an upgrade?

    ALTER TABLE  `{PREFIX}user_roles` 
      ADD COLUMN `assets_images` INT( 1 ) NOT NULL DEFAULT '1' AFTER `file_manager`;

**Comment by bossloper** [comment]
I think so. Managers will then need to proactively remove the permission from any roles they wish not to have access, but that is probably the best option as it reflects the current state. Not sure if that means it still needs adding to the 'REPLACE INTO  {PREFIX}user_roles ' section or not.

**Comment by bossloper** [comment]
Though all other permissions for roles are default to 0 and explicitly set when needed. So not sure if it would cause a problem somewhere?

**Comment by Deesen** [comment]
I added DEFAULT = 1 and also added both permissions to "REPLACE INTO" (which is meant for new installations). This way it should behave like before an upgrade, and admins can explicitly turn off KCFinder access after upgrade or new installation.

**Comment by bossloper** [comment]
with default = 1 if you add a **new** role and do not check either do they stay unchecked after the save?

**Comment by Deesen** [comment]
Yes, they behave just like all other permissions. So DEFAULT = 1 comes only into play after upgrading from 1.1 to 1.1.1, as long as a role has not been saved. After saving, the saved value will be used.

**Comment by bossloper** [comment]
I was thinking more specifically. After upgrade to 1.1.1 if a new role is added and the assets_images or assets_files permissions are not checked will they stay unchecked after saving the new role (because of the default=1)

**Comment by Deesen** [comment]
Yes it definetly stays ;-).

**Comment by bossloper** [comment]
great. sorry - just not had chance to try it myself yet!

**Comment by Fr3ddy7** [comment]
its new buttons in tree? :) images + files ?

**Comment by Deesen** [comment]
Yes, recently added and can be controlled via permissions / roles ;-)

**Pull request merged**
