### PR TITLE
Welcome 2016

### PR DESCRIPTION
**Pull request by Deesen**
Or transifex?

### CODE REVIEW

**Comment by dmi3yy** [comment]
better from transferix

**Comment by Deesen** [comment]
I changed german transifex. Maybe in future we should replace year simply via sprintf() ?

**Comment by yama** [comment]
$modx->parseText($string, array('year'=>date('Y')));
&copy; 2005-[+year+]

**Comment by Deesen** [comment]
I see in install/functions.php line 59 `$ph['current_year']`

**Pull request merged**
