### PR TITLE
1.1RC2

### PR DESCRIPTION
**Pull request by dmi3yy**

### CODE REVIEW

**Comment by janniconl** [comment]
Why is Doclister added as a default plugin, when there is no documentation at all for non-Russian speakers?

**Comment by dmi3yy** [comment]
I can remove it, and as soon as the documentation is normal to add a default.

But I think that the documentation in English will appear if doklister add immediately.
unfortunately I do not have time to do everything himself. and here without the support of the community is indispensable.

**Comment by AgelxNash** [comment]
@janniconl Read the code. It's in PHP

**Comment by janniconl** [comment]
@AgelxNash What if I and (1000s of other Modx users) users dont understand PHP enough? I am just saying, most people won't use the plugin if it is not clear how to use it.

**Comment by AgelxNash** [comment]
@janniconl You make sites on the PHP - you must learn to understand it. 5 pages of the site + hosting for $ 1 per month! = Web development.

For these projects there is no difference in the components that you use. If you want to make large sites you need to understand how it works from the inside, and for this you need to know the basics. You can start learning php from a simple component, then understand CMS, and then you will understand - there is no documentation, it's not scary.

**Pull request merged**
