### PR TITLE
More switches in install - for each type of elements

### PR DESCRIPTION
**Pull request by MrSwed**
image
and some refactor

### CODE REVIEW

**Comment by yama** [comment]
Thanks. I will restart merging after a few days off.

**Comment by Deesen** [comment]
Maybe a toggle-button is enough (maybe with float:right)?

**Comment by MrSwed** [comment]
hate "float" :)  
flexbox much better, or standart inline-block, like here, imho

It in one string at the h3, so new place no take, why one button?

**Comment by Deesen** [comment]
I also enjoy flexbox ;-)!

I just thought the toggle-buttons is already a "all/none"-button. At default all checkboxes are checked so clicking toggle once is like clicking "none". Clicking again is like "all", that was my thinking.

**Comment by MrSwed** [comment]
I think that the buttons is need - they operate on block same as global - may well be a need to operate a group as well as all switches
here "all" means all in this one group.. may be need rename, but I think it's obvious,

**Pull request merged**
