### PR TITLE
Wayfinder. Set id of reference to original document ID if it is inner doc

### PR DESCRIPTION
**Pull request by MrSwed**
… doc

### CODE REVIEW

**Comment by Jako** [comment]
Better to call the parameter useReference or something like this.

**Comment by MrSwed** [comment]
there is no such parameter
perhaps you meant useWeblinkUrl
But that is not, what is needed.
Adding this parameter determines the behavior of wayfinder as more integrated with original resource, for example, for an active menu item - will be specified class="active".

while trying to remember wherefore was done :))
I found a bug - it can not be turned off,
thanks for delay:), now fixed

**Comment by Jako** [comment]
No I meant: better name the parameter 'useReference'.

**Comment by Jako** [comment]
Could you please show the difference between useWeblinkUrl and your new parameter by an example.

**Comment by MrSwed** [comment]
useReference - not as a descriptive name.
but I agree - referenceUseOriginalID too long.

if I understand correctly, the [useWeblinkUrl ](https://github.com/MrSwed/modx-1.x-swed/blob/39058c8cf6720dc9d0fe4b7ff9789828976e9f0c/assets/snippets/wayfinder/wayfinder.inc.php#L469) defines only method of make link, as result set url referenced ID
By the way, the same thing - it is impossible to set 0) - needs to be corrected

with referenceUseOriginalID - [$usedTemplate = 'hereTpl'] (https://github.com/MrSwed/modx-1.x-swed/blob/39058c8cf6720dc9d0fe4b7ff9789828976e9f0c/assets/snippets/wayfinder/wayfinder.inc.php#L188) and [$usedTemplate = 'activeParentRowTpl';](https://github.com/MrSwed/modx-1.x-swed/blob/39058c8cf6720dc9d0fe4b7ff9789828976e9f0c/assets/snippets/wayfinder/wayfinder.inc.php#L194) will be set

**Comment by MrSwed** [comment]
I think I need another option, the link completely transforms into a document that is referenced, ie link will be fully treated as if it is the same document - displays the child resources, link attributes, title, menu, etc.

**Comment by MrSwed** [comment]
how about this name - useReferencedID ?

**Comment by MrSwed** [comment]
Okey. Now it ***useReferenced***.
Not the best realization, but allows to use fields of the original document.
If left alone 'id' - will set active, if the current.
'1' or '*' - we will use all available fields used in wayfinder
or specify a comma. In this case, it generates a database request.
Examples:
```
[[Wayfinder? &startId=`1` &useReferenced=`1`]]
[[Wayfinder? &startId=`1` &useReferenced=`id,pagetitle`]]
[[Wayfinder? &startId=`1` &useReferenced=`id,link_attributes`]]
```

**Comment by Jako** [comment]
This is the MODX Evo Weblink concept: http://wiki.modxcms.com/index.php/What_Is_A_Weblink
Wayfinder links to the target of that weblink if you use useWeblinkUrl. Is that different from your concept?

**Comment by MrSwed** [comment]
Yes, different. useWeblinkUrl processed before.
For example, there is a structure:
- Home  
  - About  
    - Company  
    - History  
  - Products  
    - Category 1  
    - Category 2  
- *News*  
  - News 1  
  - News 2  

Need menu:
- About  
  - Company  
  - History  
- Products  
  - Category 1  
  - Category 2  
- News  

So I make link for News at Home and make it menu
```modx
[[Wayfinder? &startId=`1` &level=`2` &useWeblinkUrl=1 ]]
```
and get 
```html
<ul>
 <li><a href="About">About</a>
  <ul>
   <li><a href="Company">Company</a></li>
   <li><a href="History">History</a></li>
  </ul>
 </li>
 <li><a href="Products">Products</a>
  <ul>
   <li><a href="Category1">Category 1</a></li>
   <li><a href="Category2">Category 2</a></li>
  </ul>
 </li>
 <li><a href="News">News</a></li>
</ul>
```
When you go, for example, to **About**, you see it is **active**:
```html
  <li class="active"><a href="About">About</a>
```
But, when I go to **News** in this code nothing changed! But I need same thing:
```html
<li class="active"><a href="News">News</a></li>
```
So, to achieve this, I change the ID of reference to ID of document to which it refers. Now wayfinder know current item in menu and set for it *class="active"*, 
It was in first commit.

At last, I  added possible to get fields from original, such original pagetitle, link_attributes, etc.

**Pull request merged**
