### PR TITLE
[i] #907 QuickManager 1.5.7

### PR DESCRIPTION
**Pull request by Nicola1971**
Reference: https://github.com/modxcms/evolution/issues/907
Package: https://github.com/Nicola1971/QuickManager

qm3

* New MODxRE2 Buttons
* New positions:

**left**
left-toolbar

**bottom**
bottom-toolbar

**right**
right-toolbar

**before** (position relative, before the site)
before-toolbar

### CODE REVIEW

**Comment by Nicola1971** [comment]
reverted to fix

**Comment by Nicola1971** [comment]
new option - Bottom toolbar layout

bottom-toolbar

**Comment by Fr3ddy7** [comment]
its cool :) thnx

**Comment by Fr3ddy7** [comment]
qm panel strangely leads when minimized, I would try to remove js and make a clean css

**Comment by Nicola1971** [comment]
@Fr3ddy7 you mean the ugly animation? yes i think can be done in css instead 

but, before any other additions or modification - need more testing and fix some minor issues
https://github.com/Nicola1971/QuickManager/issues

**Pull request merged**
