### PR TITLE
Sort Site tree + Menu Index GIFDevelop

### PR DESCRIPTION
**Pull request by fourroses666**
#599 + #600

### CODE REVIEW

**Comment by fourroses666** [comment]
Hope its oke now :( 
I see no conflicts :)

**Comment by Deesen** [comment]
`$_style['icons_set_parent']` is used it mutate.content.dynamic so we need to add a new key. Please change it to `$_style['icons_sort_menuindex']`

**Comment by Deesen** [comment]
:+1:

**Comment by fourroses666** [comment]
I'm getting lost a bit lol. Think its oké now. Correct me if I'm wrong :)

**Comment by Deesen** [comment]
All good I guess!

**Pull request merged**
