### PR TITLE
Remove error when "q" is an array (index.php?q[]=1)

### PR DESCRIPTION
**Pull request by Deesen**
#698

### CODE REVIEW

**Comment by yama** [comment]
Thanks, @Deesen 

https://github.com/modxcms/evolution/blob/072143e1c9793cfee51743e638e09ee8841a8f62/manager/includes/document.parser.class.inc.php#L474
Maybe you will was focused on this line ? This is a trick of the PHP syntax , not an array .
0 th character , first character , the second character ... This is to split the string on each characters.

`
if ($q[0] == '/')
`
`
if (substr($q,0,1)==='/')
`
These are the same .
I think the case such as this is , that we should be in error handling .

I think as the best solution , without resorting to the "q" parameter , and it is preferable to adopt solutions such as WordPress. That way , it becomes easy installation of the Google Custom Search Engine.

https://codex.wordpress.org/htaccess
`RewriteRule . /index.php [L]
`
It is such a thing .

**Comment by Deesen** [comment]
Thanks for taking time to explain. The error mentioned in #698 is 

`preg_match() expects parameter 2 to be string, array given in \manager\includes\document.parser.class.inc.php on line 4489` 

In MODX /.htaccess "q" is only used to deliver the resource-alias to index.php as a string. So I thought, an array will not make sense. With reset($qOrig) at least a string will be returned that can be processed without error. Not sure about a better solution.

**Comment by yama** [comment]
Thanks for your commits. I fix, this time.
https://github.com/modxcms/evolution/commit/67727686c359d18166ff3f9b3c53c1a233792ecb

**Comment by Deesen** [comment]
:+1:

**Pull request closed without merging**
