### PR TITLE
#328 Add tab "not assigned TVs" to template-edit

### PR DESCRIPTION
**Pull request by Deesen**

### CODE REVIEW

**Comment by Deesen** [comment]
And TVs are now clickable for quick editing.

**Comment by yama** [comment]
https://github.com/yama/evolution/commit/6bd0054a8db52c043a3a63b92a0a0e1de3be7ad0
Improved

**Comment by Deesen** [comment]
But if having 200 TVs, and only 10 are assigned to the template you need to scroll down a big list to find the 10. I prefer having 2 separated tabs / lists for this case. What do you think?

**Comment by Deesen** [comment]
Nice solution, thanks!

**Pull request merged**
