### PR TITLE
fixed wrong path to jquery library

### PR DESCRIPTION
**Pull request by sashabeep**
There is no jquery.min.js in /assets/plugins/managermanager/js/ so widget is not working and editing richtext field in a row is impossible due to $(function) is not defined with incorrect path to jquery

### CODE REVIEW

**Comment by dmi3yy** [comment]
Its not correct solution need fix for work with jquery 3.1.1 )

**Comment by dmi3yy** [comment]
the same PR ready few week ago )

**Comment by sashabeep** [comment]
@dmi3yy widget only works with old TimyMCE so wrong src path is not the main problem :) but it works for now

**Comment by MrSwed** [comment]
hm..
#1299
#1304

**Pull request merged**
