### PR TITLE
Manage Elements styles update

### PR DESCRIPTION
**Pull request by pmfx**

### CODE REVIEW

**Comment by Nicola1971** [comment]
@pmfx continued your work with pagetitle icon here:
https://github.com/modxcms/evolution/pull/812

**Comment by pmfx** [comment]
Thanks, good work there @Nicola1971. Could you update the rest like "Add Resource, Edit Resource, Resource Overview; Roles; Permissions; Configuration"? I think that would be all page title icons :)

**Comment by pmfx** [comment]
Ah and "Search"! ;)

**Comment by Nicola1971** [comment]
Sure.. any fontawesome suggestion for "roles" and "permission" ? It's very hard find the right icon :)

**Comment by fourroses666** [comment]
Yea hard to find good ones; Maybe something like Key / lock / universal access / child

**Comment by fourroses666** [comment]
Fa Legal

**Comment by Nicola1971** [comment]
completed: part 2
https://github.com/modxcms/evolution/pull/814

do we need pagetitle icon for default modules too? (extras and docmanager),

**Pull request merged**
