### PR TITLE
Dashboard: Fix wrong margin after resize, Version Notices

### PR DESCRIPTION
**Pull request by Deesen**

### CODE REVIEW

**Comment by pmfx** [comment]
@Deesen could you please add you ElementsInTree changes to official (kind of) repository https://github.com/pmfx/ElementsInTree ? I would like to have changes done there first and then I would move them to evo develop repo. Thanks in advance!

**Comment by Deesen** [comment]
No problem for me. But don´t you think it makes sense to keep developing it centrally here, because it has been added to core?

**Comment by pmfx** [comment]
There are pros and cons for this. Major cons for me would be that MODX releases dont happen too often while dedicated repository can make more updates/releases available for public. But if you think it would be better then we can develop it centrally and I will close my repo.

**Comment by Deesen** [comment]
Please you decide, just let me know.

**Comment by pmfx** [comment]
Cool, lets have it in [dedicated repo](https://github.com/pmfx/ElementsInTree) then :) I think "added to the core" is not quite accurate here - it just has been included as another plugin. For me "added to the core" would mean moved to /manager folder.

**Comment by Deesen** [comment]
Ok I removed it from this pull-request.

**Pull request merged**
