### PR TITLE
Readme Screenshots and ElementsInTree Update

### PR DESCRIPTION
**Pull request by pmfx**

### CODE REVIEW

**Comment by fourroses666** [comment]
@pmfx, Maybe we can spice it up? Like the example monitor?
Give me some minutes and will have a look if thats nicer.

And we need to add slack (when the invite page is done).

**Comment by fourroses666** [comment]
dashboard
resource
login

**Comment by pmfx** [comment]
@fourroses666 Nice! Replaced.

**Comment by Nicola1971** [comment]
nice ;)

**Pull request merged**
