### PR TITLE
[I] Elements -> Manage categories, version 1.2.2-beta of Jan 12, 2017

### PR DESCRIPTION
**Pull request by Deesen**
Related to #775
Based on https://github.com/pmfx/CategoriesManager

New permission "category_manager":

cat

New Button

cat1

### CODE REVIEW

**Comment by dmi3yy** [comment]
need styled to MODxRE2 
good work )

**Comment by Deesen** [comment]
cat3

**Comment by Nicola1971** [comment]
something wrong with images path

download

**Comment by Deesen** [comment]
My Firefox does not show missing images... thanks for info.

**Comment by Deesen** [comment]
Now only language-strings must be replaced by $_lang to make them translateable.

**Comment by Deesen** [comment]
catcat

**Comment by Deesen** [comment]
Anything left that needs to be done?

**Comment by Deesen** [comment]
Removed merge-conflicts

**Comment by dmi3yy** [comment]
1.2.1 only bugfix  add in 1.2.2

**Pull request merged**
