### PR TITLE
Update mutate_htmlsnippet.dynamic.php

### PR DESCRIPTION
**Pull request by bossloper**
missing : s

### CODE REVIEW

**Comment by bossloper** [comment]
or maybe as site configuration has no :s they should be removed from all snippet/chunk/mopdules/plugin pages

**Comment by Deesen** [comment]
I think removing them looks cleaner.

**Comment by bossloper** [comment]
I think I agree. 
:'s are a bit 1990s.

**Comment by Deesen** [comment]
LOL ;-)

**Comment by Deesen** [comment]
Like Kodak? ;-)

**Comment by bossloper** [comment]
:-) ... though looking at the current modx.com home page it looks like retro is in fashion.
I'll remove these colon commits.

**Pull request closed without merging**
