### PR TITLE
Delete buttons are disabled

### PR DESCRIPTION
**Pull request by Fess7**
Сan not click on the delete button in templates, snippets, plugins, tvs and etc.

### CODE REVIEW

**Comment by Deesen** [comment]
@dmi3yy Should I correct placement of class="disabled" for all subpages?

**Comment by modxuser** [comment]
If you ask me the disabled class for the buttons could be dropped completely - as the buttons still work even if the class is applied

Pretty much a waste of time having it.

**Comment by Deesen** [comment]
If you use this file, the .disabled-class is working but it is applied at wrong places in manager:
https://github.com/modxcms/evolution/blob/develop/manager/media/style/MODxRE/style.css

**Comment by Deesen** [comment]
Corrected with https://github.com/modxcms/evolution/pull/476

**Pull request merged**
