### PR TITLE
Additional Tree Buttons and general styles update

### PR DESCRIPTION
**Pull request by pmfx**
Based on new Manage Elements buttons, here are similar two for images and files.

### CODE REVIEW

**Comment by pmfx** [comment]
Preview: http://prntscr.com/brya40

**Comment by Deesen** [comment]
Very nice, thanks!

**Comment by fourroses666** [comment]
Just did a 1.1.1beta test, these buttons are nice but a bit bold?

`#topbar a, #topbar a:link, #topbar a:visited{..}`
Should we remove _font-weight:bold_ ?

And an idea to improve this (its a bit wide), I rather have a dropdown. 
I will make an example image right now.

**Comment by bossloper** [comment]
A reason for the original 'password/messages/help/ etc' to be small was it slides above the tabs on the left on a narrow screen. With the buttons they overlay the tabs which looks a bit messy.

**Comment by pmfx** [comment]
@fourroses666 Not sure about removing font-weight: bold; I have made them like that because all buttons in Manager are bold. So it is consistent. Dropdown is not possible afaik as it is inside iframe.
@bossloper Don't know anyone with screen below 1280px wide. My idea to make there more space would be to remove "Messages (0 / 0)" button. Anyone ever used it before or is using it now?

**Comment by fourroses666** [comment]
example

**Comment by fourroses666** [comment]
If it can't get above the iframe maybe slide it to the left so its hidden.
Or place these buttons on dashboard and only leave Log out ?

**Comment by bossloper** [comment]
@pmfx - I was thinking if a manager was out of the office and using a tablet for example. I too never use messaging, which would help though not sure it is the solution.

By-the-way the whole MODxRE design does not look good on an iPad2 (Safari or Chrome). It is very very small, only fills 1/4 of the screen nothing is clickable, I think it has crashed in some way and there may be a viewport scaling issue. I believe it has been like this for a few versions but personally I use MODxFlat which seems to work very well across browsers and devices.

**Pull request merged**
