### PR TITLE
Correct the use one or more "RichText" on the page

### PR DESCRIPTION
**Pull request by Fess7**

### CODE REVIEW

**Comment by Deesen** [comment]
I tested and it will break the feature of using different themes in TV-options because rendering the config-object is not in the "foreach"-loop (that is what the define(editorkey_themekey)-functions are for). You find a screenshot of it at https://github.com/modxcms/evolution/pull/548

And it will create now comma-separated list of elements for editors that can only handle single ids, so need to get instantiated one by one.

Enables only one theme:

    config_tinymce4_mini['selector'] = '#ta,#tv18,#tv19,#tv14,#tv9';
    tinymce.init(config_tinymce4_mini);

Throws error:

    CKEDITOR.replace('tv15,tv17', config_ckeditor4_mini);
    CKEDITOR.instances['tv15,tv17'].on('change', function () {
        if (CKEDITOR.instances['tv15,tv17'].checkDirty()) { documentDirty = true; }
    });

What was your issue for that pull-request?

**Comment by Deesen** [comment]
I know now what is the issue.... I switched TinyMCE4 to use config-objects but for some reason only the last get initialized... so the issue is with TinyMCE4 then.
tiny

**Comment by Fess7** [comment]
You are right, it really breaks TV-options. Sorry)

**Comment by Deesen** [comment]
But thanks for pointing out that stupid bug!

**Comment by Fess7** [comment]
Don't mention it!

**Comment by Deesen** [comment]
Fixed it I hope.. if you like to check
https://github.com/extras-evolution/tinymce4-for-modx-evo/pull/14
https://github.com/modxcms/evolution/pull/558

**Comment by Fess7** [comment]
It is working now, thank you!

**Pull request closed without merging**
