### PR TITLE
Improved/Refactored "Manage Elements"

### PR DESCRIPTION
**Pull request by Deesen**
I did not try to fix every single CSS-issue as I want to leave the final layout up to you guys. Acc. to @Nicola1971 idea I invested some time to improve "Manage Elements". Settings are remembered via localStorage like Collapsible Categories and View-Options per Tab. So snippets can use the "list"-view while chunks can use "flex"-view:

**New Button "View Options" and Collapsible Categories - using "list"-view**

mgrres1

---------------------------------------------

**Button will open new form**

mgrres2

---------------------------------------------

**Example Settings using "inline"-view**

mgrres3

---------------------------------------------

**Example Settings using "flex"-view**

mgrres4

---------------------------------------------

**Example Settings using "flex"-view**

mgrres5

### CODE REVIEW

**Comment by pmfx** [comment]
This is so cool!

**Comment by Deesen** [comment]
Oh and I forgot, the **context-menu** from "elementsInTree"-plugin available in all view-modes

mgrres6

**Comment by nick0** [comment]
This looks AWESOME!!!! It will be a sensational addition for the next version. Great work

**Comment by Nicola1971** [comment]
@Deesen has done so much nice improvements to my starting idea 
It's really a great addition, but we need (as always) help to test and fix, BEFORE next evo version :)

Most of css issue are fixed. Waiting the merge for pull css and some layout updates

mng-elements-options

**Comment by Nicola1971** [comment]
a small video demo of new Manage Elements
https://youtu.be/-dooZgaWiHY

**Comment by pmfx** [comment]
On the video it looks even better. Amazing addition guys!

**Comment by dmi3yy** [comment]
Nice!

Отправлено с iPhone

**Comment by janniconl** [comment]
Looks great guys. Good effort!
- Maybe the font size of the View Options could be a bit smaller?

- Can't this arrow/chevron be removed from css? It seems a bit too much icons :-)
afbeelding

- I redesigned the RE2 theme a bit myself, so I can easily edit it for customers, changing the blue to another color. Maybe these screenshots can be of inspiration for you guys:

afbeelding
afbeelding

**Comment by dmi3yy** [comment]
can fix ?
Conflicting files
manager/actions/resources.static.php
manager/media/style/MODxRE2/style.css

**Comment by Deesen** [comment]
Ok conflicts should be solved.

**Comment by Nicola1971** [comment]
styles finish here https://github.com/modxcms/evolution/pull/1258

**Pull request merged**
